<MenuScreen>:
    canvas.before:
        Color:
            rgba: 1,1,0,1
        Rectangle:
            pos:self.pos
            size:self.size
    BoxLayout:
        orietation: 'vertical'
        padding: '20dp'
        spacing: '20dp'
       
        Label:
            text: 'Cosmo Adventure'
            font_name: 'assets/Comforter-Regular.ttf'
            font_size: '30dp'
            color: 'red'
            size_hint_y: .2 